name : Deploy to lambda
on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "main" ] # for test purpose

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -v -o main ./tester/psychological/main/main.go
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r deployment.zip . -i main

      - name: Deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "ap-northeast-2"
          function_name: my-go-lambda-function
          zip_file: deployment.zip
          memory_size: 128
          timeout: 10
          runtime: nodejs12.x

